name: dqn_paper
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - ca-certificates=2021.7.5=h06a4308_1
  - certifi=2021.5.30=py38h06a4308_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgomp=9.3.0=h5101ec6_17
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - ncurses=6.2=he6710b0_1
  - openssl=1.1.1l=h7f8727e_0
  - pip=21.0.1=py38h06a4308_0
  - python=3.8.11=h12debd9_0_cpython
  - readline=8.1=h27cfd23_0
  - setuptools=52.0.0=py38h06a4308_0
  - sqlite=3.36.0=hc218d9a_0
  - tk=8.6.10=hbc83047_0
  - wheel=0.37.0=pyhd3eb1b0_1
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - absl-py==0.13.0
    - atari-py==0.2.9
    - cachetools==4.2.2
    - charset-normalizer==2.0.4
    - click==8.0.1
    - cloudpickle==1.6.0
    - configparser==5.0.2
    - cycler==0.10.0
    - docker-pycreds==0.4.0
    - gitdb==4.0.7
    - gitpython==3.1.18
    - google-auth==1.35.0
    - google-auth-oauthlib==0.4.6
    - grpcio==1.40.0
    - gym==0.19.0
    - idna==3.2
    - kiwisolver==1.3.2
    - markdown==3.3.4
    - matplotlib==3.4.3
    - numpy==1.21.2
    - oauthlib==3.1.1
    - opencv-python==4.5.3.56
    - pandas==1.3.3
    - pathtools==0.1.2
    - pillow==8.3.2
    - promise==2.3
    - protobuf==3.17.3
    - psutil==5.8.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyglet==1.5.11
    - pyopengl==3.1.5
    - pyopengl-accelerate==3.1.5
    - pyparsing==2.4.7
    - python-dateutil==2.8.2
    - pytz==2021.1
    - pyyaml==5.4.1
    - requests==2.26.0
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - sentry-sdk==1.3.1
    - shortuuid==1.0.1
    - six==1.16.0
    - smmap==4.0.0
    - stable-baselines3==1.2.0
    - subprocess32==3.5.4
    - tensorboard==2.6.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - torch==1.9.0
    - typing-extensions==3.10.0.2
    - urllib3==1.26.6
    - wandb==0.12.1
    - werkzeug==2.0.1
prefix: /home/marktrovinger/miniconda3/envs/dqn_paper
